// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFY0bRmcCRGkfgBscgSJI6T8wj_Y7hSRQ',
    appId: '1:982011977114:web:5d03adc24ebbcddb9e6e23',
    messagingSenderId: '982011977114',
    projectId: 'zv-transport-gbr-app',
    authDomain: 'zv-transport-gbr-app.firebaseapp.com',
    storageBucket: 'zv-transport-gbr-app.firebasestorage.app',
    measurementId: 'G-YN1ESYD7LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAYbD1jUadklAKR53fKZ5uAmEI-VuuQo8',
    appId: '1:982011977114:android:342ca1df4ad465859e6e23',
    messagingSenderId: '982011977114',
    projectId: 'zv-transport-gbr-app',
    storageBucket: 'zv-transport-gbr-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATIpvxlFSwx5zoboMqx7baWQhn9hRiyek',
    appId: '1:982011977114:ios:81826828203b0d479e6e23',
    messagingSenderId: '982011977114',
    projectId: 'zv-transport-gbr-app',
    storageBucket: 'zv-transport-gbr-app.firebasestorage.app',
    iosBundleId: 'com.example.zvTransportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATIpvxlFSwx5zoboMqx7baWQhn9hRiyek',
    appId: '1:982011977114:ios:81826828203b0d479e6e23',
    messagingSenderId: '982011977114',
    projectId: 'zv-transport-gbr-app',
    storageBucket: 'zv-transport-gbr-app.firebasestorage.app',
    iosBundleId: 'com.example.zvTransportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFY0bRmcCRGkfgBscgSJI6T8wj_Y7hSRQ',
    appId: '1:982011977114:web:729c35f463c9bad19e6e23',
    messagingSenderId: '982011977114',
    projectId: 'zv-transport-gbr-app',
    authDomain: 'zv-transport-gbr-app.firebaseapp.com',
    storageBucket: 'zv-transport-gbr-app.firebasestorage.app',
    measurementId: 'G-C2ZRH4YFKC',
  );
}
